export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'row',
    gap: '32px',
  },
  convertWrapper: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '50%',
  },
  resultsWrapper: {
    display: 'flex',
    flexDirection: 'column',
    border: '1px solid transparent',
    borderRadius: '12px',
    padding: '32px',
    width: '50%',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-all',
    boxShadow: 'inset 0px 4px 4px rgba(0, 0, 0, 0.05)',
    backgroundColor: '#E4EFF0',
  },
  textField: {
    width: '100%',
    marginBottom: '24px',
    backgroundColor: '#F5F5F5',
    borderRadius: '8px',
    boxShadow: '0px 1px 2px rgba(0, 0, 0, 0.25)',
  },
  options: {
    display: 'flex',
    justifyContent: 'space-between',
    width: '100%',
    gap: '24px',
    alignItems: 'center',
    marginBottom: '32px',
  },
  optionsField: {
    width: '50%',
    height: '56px',
    backgroundColor: '#F5F5F5',
    borderRadius: '8px',
    boxShadow: '0px 1px 2px rgba(0, 0, 0, 0.25)',
  },
  convertButton: {
    textTransform: 'none',
    width: '190px',
    height: '56px',
    backgroundColor: '#0E59EC',
    borderRadius: '12px',
    marginBottom: '32px',
  },

  resultsButton: {
    display: 'flex',
    flex: 'none',
    flexDirection: 'row',
    gap: '8px',
    textTransform: 'none',
    borderRadius: '12px',
    borderColor: '#0e59ec',
    maxWidth: '190px',
    height: '56px',
  },
};
